### ISSUE TITLE
[ xhelp latest version ] create staff occur error

### ISSUE THREAD

**Issue by Jacky1204** [XoopsModules25x/xhelp#8]
When I try to add staff on xhelp web interface, error occur. Below is the error message:

Error : TypeError: Argument 1 passed to XoopsModules\Xhelp\StaffHandler::isStaff() must be of the type int, string given, called in /var/www/xoops/modules/xhelp/admin/staff.php on line 901

Please help to investigation !! Thank you

**Comment by alain01** [comment]
Hello,
XOOPS version, PHP version
xhelp version ("latest" is not a reliable information ;-))

**Comment by Jacky1204** [comment]
Hi, 

The xoops version is 2.5.10
PHP version is 7.4.30
xhelp version is 1.0.0 Alpha 3

**Comment by alain01** [comment]
Same with me on
XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 8.1.8
MySQL Version | 8.0.29

line 901 (/modules/xhelp/admin/staff.php)
```
        if ($staffHandler->isStaff($uid)) {
            $helper->redirect('admin/staff.php?op=manageStaff', 3, _AM_XHELP_STAFF_EXISTS);
        }

```

**Comment by ggoffy** [comment]
I will look into it this afternoon

**Comment by alain01** [comment]
ok ;-) cool.
I found another bugs too, you' re welcome !

**Comment by ggoffy** [comment]
I have fixed several type cast errors

please test my version from https://github.com/ggoffy/xhelp

if it works I will make a pull request to XoopsModules25x

**Comment by alain01** [comment]
ok, T Y. 
I test...

**Comment by alain01** [comment]
/modules/xhelp/admin/about.php 

Error : TypeError: mktime(): Argument #5 ($day) must be of type ?int, string given

**Comment by ggoffy** [comment]
in file /Frameworks/moduleclasses/moduleadmin/moduleadmin.php line 506

this is an error in the XOOPS core

**Comment by alain01** [comment]
hummm so ?

and when I want to create role,
I get error:
Tab Staff / button Create New Role / type name, description and selected button
Then I click on the "Create New Role"

"Not Found
The requested URL was not found on this server."

(http://mysite.com/modules/xhelp/staff.php?op=manageStaff)

THen the Role is created even I've seen this bad page

And When I want to remove Role, "Error: role was not removed."

Update doesn't work, I add some right, click on update then come back to the right list, 
No update.

**Comment by mambax7** [comment]
Thanks Goffy for looking into it. I'll look into your changes this weekend, and I also have some updates that I didn't commit yet. Hopefully, together we can fix it. 

@Jacky1204 and @alain01: thanks for the testing and reporting the issues. Please remember: this is just Alpha, so bugs are expected, but thanks to your testing, hopefully we'll be able to fix them!

**Comment by mambax7** [comment]
@alain01 for the error in about.php, this is solved here: https://github.com/mambax7/xhelp/commit/54e248e8b7e58251e6265c0a5d096d757a20bd93
Just delete the "NOT RELEASED" in $modversion['release_date']

**Comment by ggoffy** [comment]
Hi
I have checked now the module with PHPStorm Inspect Code and I fixed all errors I found and where I have known how to fix them. there are still tons of warnings left but in a first step I want to get the module running.
I testet on admin site to create roles, departments and staffs and also deleting them. 

please continue testing the module.

**Comment by alain01** [comment]
OK, Thank you, I will test tonight.

**Comment by Jacky1204** [comment]
Hi ggoffy,
I try to add staff on xhelp web interface, error is still occur. Below is the outcome message. Thank you.

Error : TypeError: Argument 2 passed to XoopsModules\Xhelp\EventService::advise() must be an instance of XoopsModules\Xhelp\mixed, instance of XoopsModules\Xhelp\NotificationService given, called in /var/www/xoops/modules/xhelp/class/Service.php on line 42

**Comment by alain01** [comment]
Hi,
it seems to be ok with me.

Jacky,
you should create 1 role before staff. (for example: Manager)
Do you create it ?

**Comment by ggoffy** [comment]
hi Jacky1204

I do not get the error. 
did you test the version from https://github.com/ggoffy/xhelp ?
did you clean the cache ?

**Comment by Jacky1204** [comment]
> Hi, it seems to be ok with me.
> 
> Jacky, you should create 1 role before staff. (for example: Manager) Do you create it ?

Yes, I created role but it is still error

**Comment by Jacky1204** [comment]
> hi Jacky1204
> 
> I do not get the error. did you test the version from https://github.com/ggoffy/xhelp ? did you clean the cache ?

Hi ggoffy,

I test the version is Alpha 4 and clean the cache. But it is still error. So strange.

**Comment by ggoffy** [comment]
I have no executable Xoops 2.5.10 on my laptop. can you please test with 2.5.11 ?

**Comment by alain01** [comment]
2.5.11 beta 2 ;-)))

**Comment by ggoffy** [comment]
@Jacky1204 any results of testing?

**Comment by ggoffy** [comment]
@alain01 
have you found any bug? if not I will push my changes to xoopsmodules25

**Comment by alain01** [comment]
My last simple tests were ok (25/08/2022).
Sorry, I'm so busy @ work and @ Home ATM
